# baseurl = "https://example.com/"
relativeURLs = true
# remember trailing / at end of baseurl
languageCode = "en-GB"
title = "Ben Hayward"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
paginate = 50
theme = "sublime-hugo"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Ben Hayward"
	description = "Web & Blockchain Developer."
	copyright = "MIT"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "The requested page was not <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Ben Hayward"
	bio = ""
	bio2 = ""
	subscribe = "Subscribe"
	followme = "Contact"

	# Enable Google search
	search_enabled = true
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "benhayward.ben@gmail.com"
		url = "mailto:benhayward.ben@gmail.com"
